### ISSUE TITLE
Any plans to make this compatible with PHP 8.x?

### ISSUE THREAD

**Issue by niel** [dborsatto/php-giantbomb#11]
Tried updating an old project using this and was prevented from using it because of the requirement for "php ^7.4" and I'm using 8.0.

**Comment by dborsatto** [comment]
Hey @niel yes, I want to make this PHP 8 compatible, I just have not found the time to work on this yet (plus nobody was asking for it, so it was not really a priority). I'll try to do it in the next few days :+1:

**Comment by dborsatto** [comment]
Fixed with #12 and published in [v2.2.0](https://github.com/dborsatto/php-giantbomb/releases/tag/v2.2.0)

**Comment by niel** [comment]
Many thanks.
