### ISSUE TITLE
Query by relationship

### ISSUE THREAD

**Issue by PiousVenom** [dborsatto/php-giantbomb#13]
If I want to do a query for games on a specific platform, how would that be?

**Comment by dborsatto** [comment]
Hey @PiousVenom,

this library is a simple layer on top of the actual API, so [their docs](https://www.giantbomb.com/api/documentation/#toc-0-17) are a good resource for your needs.

For your query, I believe this is the right approach:

```php
$query = DBorsatto\GiantBomb\Query::create()
    ->addFilterBy('platforms', 'PS4,PS5'); // You might want to experiment with casing, I'm not sure
$games = $client->find('Game', $query);
```
