### ISSUE TITLE
Update to Guzzle 7

### ISSUE THREAD

**Issue by ghost** [dborsatto/php-giantbomb#8]
Any way this package could be updated to use Guzzle 7? It's holding my application upgrade back :-)

**Comment by dborsatto** [comment]
Hey there! Yeah, if there's a need to update then I'll gladly do it. To be honest I wasn't sure anybody was using it so haven't even thought about upgrading it. I hope I'll get it done this weekend!

**Comment by ghost** [comment]
I tried doing it myself today but when upgrading PHPUnit it throws all kinds of errors I don't know how to fix.

**Comment by dborsatto** [comment]
I'm working on a PR (it's the only open one) which fixes this and a whole bunch of other stuff I've been waiting for the right occasion to fix. It's going to be a major release because master already had some breaking changes in how the cache system works, so I'm fixing some architectural issues that were present in v1. It only needs a few tests, I hope I'll get it done tonight.

**Comment by ghost** [comment]
Thanks!

**Comment by dborsatto** [comment]
Fixed in #9

**Comment by dborsatto** [comment]
@Fossil01 I don't have a proper upgrade guide, tbh the effort is not really worth it. I have updated the examples in the README to reflect the changes, if you have questions just let me know.

The main change is that the concept of repository was a weird mix of competences so it no longer exists in such form, therefore querying is slightly different. The client now exposes the `find` and `findOne` methods which take the name of resource to be queried (Game, Franchise, etc) and a `DBorsatto\GiantBomb\Query` object, so there's no longer a `query` method which created the object. I believe the current approach makes more sense as you have an object which is responsible for actually calling the API (the client) and another which is responsible for filtering for the API call (the query), whereas earlier there were client, repository and query which all kind of shared some responsibilities and the execution flow was really weird...

**Comment by ghost** [comment]
Roger that. Thanks for the work!
